author: Chao Gu
title: Chao Gu
url: "https://guch8017.github.io"
baseurl: "/researcher"
description: "About Chao Gu"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/guch8017"
footer_text: "Page designed by Ankit Sultana and modified by C. Gu and K. Lin"

sass:
  sass_dir: _sass

nav:
  - name: "About"
    link: "/researcher/"
  - name: "CV"
    link: "CV_KeLin.pdf"
  - name: "Contact"
    link: "contact"
