author: Ke Lin
title: Ke Lin
url: "https://leonardodalinky.github.io"
baseurl: "/researcher"
description: "About Ke Lin"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/leonardodalinky"
footer_text: "Page designed by Ankit Sultana and modified by K. Lin"

sass:
  sass_dir: _sass

nav:
  - name: "About"
    link: "/researcher/"
  - name: "CV"
    link: "CV_KeLin.pdf"
  - name: "Contact"
    link: "contact"
